//
//  PodcastModel.swift
//  WylsacomAppPrototype
//
//  Created by Ilya Volkov on 28.09.2022.
//

struct PodcastModel {
    static func getData() -> [Cell] {
        return [
            Cell(image: "release16",
                 title: "Podcast mini: предновогодний",
                 subTitle: "Выпуск #16",
                 date: "33 мин · 23 декабря 2021"),
            Cell(image: "release15",
                 title: "Podcast mini: про наши машиныи сколько я потратил на свою M5",
                 subTitle: "Выпуск #15",
                 date: "41 мин · 20 октября 2021"),
            Cell(image: "release14",
                 title: "Podcast mini: об очередной блокировке YouTube в России",
                 subTitle: "Выпуск #14",
                 date: "9 мин · 29 сентября 2021"),
            Cell(image: "release13",
                 title: "Podcast mini: про контент",
                 subTitle: "Выпуск #13",
                 date: "15 мин · 17 августа 2021"),
            Cell(image: "release12",
                 title: "Podcast mini: Apple сканирует твой iPhone",
                 subTitle: "Выпуск #12",
                 date: "6 мин · 6 августа 2021"),
            Cell(image: "release11",
                 title: "Podcast mini: про M5 CS, наши против финнов, Бузова против Губерниева и вообще...",
                 subTitle: "Выпуск #11",
                 date: "16 мин · 16 июня 2021"),
            Cell(image: "release10",
                 title: "Podcast mini: где новинки, Apple? Как я пытался китайскую машину полюбить",
                 subTitle: "Выпуск #10",
                 date: "21 мин · 19 марта 2021"),
            Cell(image: "release9",
                 title: "Podcast mini: Роскомнадзор наехал на Twitter, а я сдал генетический тест",
                 subTitle: "Выпуск #9",
                 date: "14 мин · 1 марта 2021"),
            Cell(image: "release8",
                 title: "Podcast mini: сказ о том, как я в ГИБДД ходил фантомные штрафы оплачивать",
                 subTitle: "Выпуск #8",
                 date: "16 мин · 26 февраля 2021"),
            Cell(image: "release7",
                 title: "Podcast mini: про PS5 VR, новые MacBook и скорую презентацию Apple",
                 subTitle: "Выпуск #7",
                 date: "16 мин · 24 февраля 2021"),
            Cell(image: "release6",
                 title: "Podcast mini: в интернете опять запретили ругаться матом, блядь",
                 subTitle: "Выпуск #6",
                 date: "15 мин · 1 февраля 2021"),
            Cell(image: "release5",
                 title: "Podcast mini: Apple заработала $111,4 миллиарда, Ведьмак 3 и новая Tesla Model S",
                 subTitle: "Выпуск #5",
                 date: "10 мин · 28 января 2021"),
            Cell(image: "release4",
                 title: "Podcast mini: iPhone SE Plus на весну и странная Sony",
                 subTitle: "Выпуск #4",
                 date: "12 мин · 25 января 2021"),
            Cell(image: "release3",
                 title: "Podcast mini: что покажет Apple в 2021 году?",
                 subTitle: "Выпуск #3",
                 date: "16 мин · 22 января 2021"),
            Cell(image: "release2",
                 title: "Podcast mini: время - главный ресурс, научись им управлять",
                 subTitle: "Выпуск #2",
                 date: "16 мин · 21 января 2021"),
            Cell(image: "release1",
                 title: "Podcast mini: дворец Путина и чувство вкуса на Руси",
                 subTitle: "Выпуск #1",
                 date: "12 мин · 20 января 2021"),
        ]
    }
}
